#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

[ -n "$CI" ] && exit 0

# npm run prettier:fix  # to add when a javacript file is present
# git add *\*.js
npm run validate
git add *\*.md 
npx --no-install lint-staged